#!/usr/bin/env python3
"""Regenerates GSNormalizeData.h (canonical normalization data for the BMP) from Python's Unicode database:
    python3 Source/GSNormalizeData.py > Source/GSNormalizeData.h
Used by NSString (-decomposedStringWithCanonicalMapping / -precomposedStringWithCanonicalMapping) when GNUstep is
built without ICU."""
import sys, unicodedata

full = {}
for c in range(0x10000):
    if 0xD800 <= c < 0xE000 or 0xAC00 <= c <= 0xD7A3:     # surrogates; Hangul is algorithmic
        continue
    d = unicodedata.normalize('NFD', chr(c))
    if d != chr(c) and all(ord(x) < 0x10000 for x in d):
        full[c] = [ord(x) for x in d]
pairs = []
for c in range(0x10000):
    if 0xD800 <= c < 0xE000:
        continue
    dd = unicodedata.decomposition(chr(c))
    if not dd or dd.startswith('<'):
        continue
    p = [int(x, 16) for x in dd.split()]
    if len(p) != 2 or p[0] > 0xFFFF or p[1] > 0xFFFF:
        continue
    if unicodedata.normalize('NFC', chr(p[0]) + chr(p[1])) != chr(c):
        continue                                           # composition exclusion
    pairs.append((p[0], p[1], c))
pairs.sort()
ccc = [(c, unicodedata.combining(chr(c))) for c in range(0x10000)
       if not 0xD800 <= c < 0xE000 and unicodedata.combining(chr(c))]
w = sys.stdout.write
w('/* GSNormalizeData.h: canonical normalization data for the BMP, Unicode %s.\n'
  ' * Generated by GSNormalizeData.py from the Unicode Character Database; used by NSString when GNUstep is built\n'
  ' * without ICU. */\n' % unicodedata.unidata_version)
chars, idx = [], []
for c in sorted(full):
    idx.append((c, len(chars), len(full[c])))
    chars += full[c]
w('static const unsigned short GSNormDecomp[][2] = { /* code point, index into GSNormDecompChars */\n')
w(''.join('  { 0x%04X, %d },\n' % (c, i) for c, i, l in idx)); w('};\n')
w('static const unsigned char GSNormDecompLen[] = {' + ','.join(str(l) for c, i, l in idx) + '};\n')
w('static const unsigned short GSNormDecompChars[] = {' + ','.join('0x%04X' % x for x in chars) + '};\n')
w('static const unsigned short GSNormPairs[][3] = {\n' + ''.join('  { 0x%04X, 0x%04X, 0x%04X },\n' % p for p in pairs) + '};\n')
w('static const unsigned short GSNormClasses[][2] = {\n' + ''.join('  { 0x%04X, %d },\n' % p for p in ccc) + '};\n')
